# Use uma imagem base do Python 3.11
FROM python:3.11

# Defina o diretório de trabalho no contêiner
WORKDIR /app

# Copie os arquivos do projeto para o diretório de trabalho no contêiner
COPY . /app

# Instale as dependências do projeto listadas no requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Exponha a porta padrão do Streamlit
EXPOSE 8501

# Comando para iniciar o Streamlit
CMD ["streamlit", "run", "Dieta.py", "--server.port=8501", "--server.address=0.0.0.0"]


